function toppings (topping: string) {
    circle = sprites.create(img`
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        .............................................ddddddddddddddddddd........................................................
        .........................................ddddddddddddddddddddddddddd....................................................
        .......................................ddddddddddddddddddddddddddddddd..................................................
        ....................................ddddddddddddddddddddddddddddddddddddd...............................................
        ..................................ddddddddddddddddddddddddddddddddddddddddd.............................................
        ................................ddddddddddddddddddddddddddddddddddddddddddddd...........................................
        ...............................ddddddddddddddddddddddddddddddddddddddddddddddd..........................................
        .............................ddddddddddddddddddddddddddddddddddddddddddddddddddd........................................
        ............................ddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................................
        ...........................ddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................................
        .........................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd....................................
        ........................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...................................
        .......................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..................................
        ......................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.................................
        .....................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd................................
        .....................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd................................
        ....................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...............................
        ...................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..............................
        ..................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.............................
        ..................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.............................
        .................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................
        ................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...........................
        ................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...........................
        ...............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..........................
        ...............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..........................
        ..............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.........................
        ..............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.........................
        ..............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.........................
        .............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd........................
        .............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd........................
        ............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................
        ............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................
        ............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................
        ............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ...........ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................
        ............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................
        ............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................
        ............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................
        ............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................
        .............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd........................
        .............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd........................
        ..............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.........................
        ..............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.........................
        ..............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.........................
        ...............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..........................
        ...............ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..........................
        ................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...........................
        ................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...........................
        .................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................
        ..................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.............................
        ..................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.............................
        ...................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..............................
        ....................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...............................
        .....................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd................................
        .....................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd................................
        ......................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.................................
        .......................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..................................
        ........................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...................................
        .........................ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd....................................
        ...........................ddddddddddddddddddddddddddddddddddddddddddddddddddddddd......................................
        ............................ddddddddddddddddddddddddddddddddddddddddddddddddddddd.......................................
        .............................ddddddddddddddddddddddddddddddddddddddddddddddddddd........................................
        ...............................ddddddddddddddddddddddddddddddddddddddddddddddd..........................................
        ................................ddddddddddddddddddddddddddddddddddddddddddddd...........................................
        ..................................ddddddddddddddddddddddddddddddddddddddddd.............................................
        ....................................ddddddddddddddddddddddddddddddddddddd...............................................
        .......................................ddddddddddddddddddddddddddddddd..................................................
        .........................................ddddddddddddddddddddddddddd....................................................
        .............................................ddddddddddddddddddd........................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        `, SpriteKind.Player)
}
let circle: Sprite = null
let square: Sprite = null
scene.setBackgroundColor(3)
game.splash("How to make a pizza!")
let isSquare = game.ask("A= square pizza", "B= circle pizza")
if (isSquare) {
    square = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . d d d d d d d d d d . . 
        . . . . d d d d d d d d d d . . 
        . . . . d d d d d d d d d d . . 
        . . . . d d d d d d d d d d . . 
        . . . . d d d d d d d d d d . . 
        . . . . d d d d d d d d d d . . 
        . . . . d d d d d d d d d d . . 
        . . . . d d d d d d d d d d . . 
        . . . . d d d d d d d d d d . . 
        . . . . d d d d d d d d d d . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Player)
    square.setPosition(78, 60)
} else {
    circle = sprites.create(img`
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        ..........................................................3333333333333333333...........................................
        ......................................................3333ddddddddddddddddddd3333.......................................
        ...................................................333ddddddddddddddddddddddddddd333....................................
        .................................................33ddddddddddddddddddddddddddddddddd33..................................
        ...............................................33ddddddddddddddddddddddddddddddddddddd33................................
        .............................................33ddddddddddddddddddddddddddddddddddddddddd33..............................
        ...........................................33ddddddddddddddddddddddddddddddddddddddddddddd33............................
        ..........................................3ddddddddddddddddddddddddddddddddddddddddddddddddd3...........................
        ........................................33ddddddddddddddddddddddddddddddddddddddddddddddddddd33.........................
        .......................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........................
        ......................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......................
        .....................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3......................
        ...................................33ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd33....................
        ..................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...................
        ..................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...................
        .................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3..................
        ................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.................
        ...............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3................
        ..............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...............
        ..............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...............
        .............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3..............
        ............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.............
        ............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.............
        ...........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3............
        ...........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3............
        ..........................dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...........
        ..........................dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...........
        .........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3..........
        .........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3..........
        ........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.........
        ........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.........
        ........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.........
        .......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........
        .......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........
        .......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........
        .......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        ......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......
        .......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........
        .......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........
        .......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........
        .......................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........
        ........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.........
        ........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.........
        ........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.........
        .........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3..........
        .........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3..........
        ..........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...........
        ..........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...........
        ...........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3............
        ...........................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3............
        ............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.............
        ............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.............
        .............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3..............
        ..............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...............
        ..............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...............
        ...............................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3................
        ................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.................
        .................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3..................
        ..................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...................
        ..................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3...................
        ...................................33ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd33....................
        .....................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3......................
        ......................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd3.......................
        .......................................3ddddddddddddddddddddddddddddddddddddddddddddddddddddddd3........................
        ........................................33ddddddddddddddddddddddddddddddddddddddddddddddddddd33.........................
        ..........................................3ddddddddddddddddddddddddddddddddddddddddddddddddd3...........................
        ...........................................33ddddddddddddddddddddddddddddddddddddddddddddd33............................
        .............................................33ddddddddddddddddddddddddddddddddddddddddd33..............................
        ...............................................33ddddddddddddddddddddddddddddddddddddd33................................
        .................................................33ddddddddddddddddddddddddddddddddd33..................................
        ...................................................333ddddddddddddddddddddddddddd333....................................
        ......................................................3333ddddddddddddddddddd3333.......................................
        ..........................................................3333333333333333333...........................................
        ........................................................................................................................
        ........................................................................................................................
        ........................................................................................................................
        `, SpriteKind.Player)
    circle.setPosition(76, 61)
}
